version: '3'

services:
  login: 
    build: ./login
    ports:
     - "8001:8001"
    env_file:
      - .env

  task: 
    build: ./task
    ports:
      - "8002:8002"
    env_file:
      - .env 

  image_process:
    build: ./image_process
    ports:  
      - "8003:8003"

  user:
    build: ./user
    ports:
      - "8004:8004"
      
  gateway:
    build: ./gateway
    ports:
      - "8000:80"
    depends_on:
      - login
      - task
      - image_process
      - user